// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://iqntjhscndzpafxspclk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImlxbnRqaHNjbmR6cGFmeHNwY2xrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTg0NTU0NjUsImV4cCI6MjA3NDAzMTQ2NX0.leCSltuYHOhYGTbL5VrHS9phpRT377LXj17Vg9GZ4Yw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});